src/app/post/page.jsx
=> feat: 게시글목록페이지 생성

src/app/user/location-management/page.jsx
- 기존 `alert()` 방식에서 `ConfirmModal` 컴포넌트 사용으로 변경
- `MODAL_TYPES.CONFIRM_ONLY` 타입으로 확인 전용 모달 구현
- **변경사항 감지**: 초기 상태와 현재 상태 비교를 통한 실시간 감지
- **동적 버튼 제어**: 변경사항이 있을 때만 저장 버튼 활성화
- **시각적 피드백**: 버튼 색상 및 커서 상태로 사용자에게 명확한 상태 전달
- `useRef`를 활용한 초기 상태 저장 및 메모리 효율성 개선
- `JSON.stringify` 기반 깊은 비교로 정확한 변경사항 감지
- 저장 완료 시 초기 상태 업데이트로 일관된 상태 관리
```javascript
// 초기 상태 저장
const initialAreas = useRef([]);
// 변경사항 감지 로직
const hasChanges = JSON.stringify(selectedAreas) !== JSON.stringify(initialAreas.current);
=> feat: 거래지역 관리 - 저장 완료 모달 및 버튼 활성화 로직 추가

src/app/(user)/mypage/page.jsx, src/components/common/WishlistSidebar.jsx
- WishlistSidebar에 sidebarKey=wishlist 추가
- 마이페이지 메뉴에서 찜한 상품 클릭 시 사이드바 열림
=> feat: 마이페이지에 찜한 상품 사이드바 연동

src/app/(user)/mypage/page.jsx
중복 데이터 제거, 작성 리뷰 클릭이 아닌 숫자 클릭 시 리뷰 내역 사이드 바 생성 수정
=> fix: 오류 제거

src/app/(user)/login/page.jsx, src/app/(user)/signup/complete/page.jsx, src/app/(user)/signup/page.jsx, src/app/ClientLayout.jsx
- 로그인 페이지에 회원가입 링크 추가
- 모든 인증 페이지 로고 클릭 시 홈으로 이동 기능 추가
- Next.js Link 컴포넌트로 연결
- 로그인, 회원가입, 회원가입 완료 페이지에 적용
=> feat: 인증 페이지 간 네비게이션 링크 추가

src/app/post/[id]/page.jsx, src/app/post/page.jsx
=> feat:게시글상세조회기능추가

src/app/product/search/page.jsx
- useSearchParams, useRouter, usePathname 도입하여 soft navigation 시 쿼리 변경 감지
- 기존 window.location.search 기반 초기 1회 실행 로직을 searchParams 의존 useEffect로 변경
- 카테고리 클릭 및 브레드크럼 이동 시 router.push로 URL 업데이트
- 상태 변화에 따라 검색어, 카테고리 경로, 선택 카테고리 자동 갱신
- 코드 주석 전면 수정으로 가독성 및 유지보수성 향상
=> feat(search): 검색 페이지 URL 쿼리 변경 감지 및 상태 동기화 로직 개선

src/app/(user)/additional-info/additional-info.css, src/app/(user)/additional-info/page.jsx, src/app/(user)/login/page.jsx, src/app/(user)/signup/complete/page.jsx, src/app/(user)/signup/complete/signup-complete.css, src/app/(user)/signup/page.jsx, src/app/ClientLayout.jsx
- 카카오 로그인 버튼 기능 구현 (로그인 → 추가정보 입력)
- 추가정보 입력 페이지 완전 구현 (닉네임 검증, 주소 검색, 개인정보 동의)
- 회원가입 완료 페이지 조건부 렌더링 (from 파라미터 기반)
- 닉네임 URL 파라미터 전달로 개인화 환영 메시지 구현
- 일반 회원가입과 카카오 회원가입 플로우 완전 분리
=> feat: 추가정보 입력 페이지 완성

src/app/post/[id]/page.jsx, src/app/post/components/Editor.jsx, src/app/post/write/page.jsx
=> modify:공동구매참여여부기능수정

src/app/(user)/additional-info/additional-info.css, src/app/(user)/additional-info/page.jsx, src/app/(user)/components/addressUtils.js, src/app/(user)/components/components.jsx, src/app/(user)/components/duplicateUtils.js, src/app/(user)/components/passwordUtils.js, src/app/(user)/components/phoneUtils.js, src/app/(user)/components/usePasswordInput.js, src/app/(user)/login/login.css, src/app/(user)/login/page.jsx, src/app/(user)/signup/complete/page.jsx, src/app/(user)/signup/complete/signup-complete.css, src/app/(user)/signup/page.jsx, src/app/(user)/signup/signup.css, src/store/userStore.js
-  **비밀번호 검증** 유틸리티 분리 (강화된 규칙 적용)
-  **핸드폰 번호** 포맷팅 유틸리티 분리
-  **주소 처리** 유틸리티 분리 (도로명 주소 우선)
-  **중복 확인** 유틸리티 분리
-  **재사용성** 대폭 향상 (비밀번호 변경, 프로필 수정 등에서 활용 가능)
=> feat: 회원가입 시스템 컴포넌트 분리 및 유틸리티 모듈화

src/app/(user)/mypage/page.jsx, src/app/(user)/profile-edit/page.jsx, src/app/(user)/profile-edit/profile-edit.css
- 닉네임/이메일/휴대전화번호 수정
- 실시간 검증 및 중복 확인
- 사이드바 UI로 마이페이지 연동
- 기존 유틸리티 재사용
=> feat: 프로필 수정 기능 구현

src/app/(user)/components/duplicateUtils.js, src/app/(user)/login/page.jsx, src/app/(user)/mypage/page.jsx, src/app/(user)/signup/page.jsx, src/components/common/Header.jsx, src/lib/api.js, src/store/userStore.js
- 사용자 인증(로그인/회원가입) 백엔드 연동 완료
- Zustand 상태 관리 최적화 (무한 루프 해결)
- CORS 설정 및 Gateway 연동
- HttpOnly 쿠키 기반 인증 구현
- 마이페이지 인증 확인 로직 개선
- Header.jsx 로그인 상태 연결 위해 코드 수정
- api.js 쿠키 추가로 인해 코드 수정
=> feat: 백엔드 API 연동 및 인증 시스템 구현

src/app/(user)/signup/page.jsx, src/lib/api.js
- withCredentials: true 추가 (쿠키 지원)
- localStorage 토큰 방식 유지 (호환성)
- Gateway 연동을 위한 baseURL 변경
- 백엔드 User Service 연동 완료
=> feat: API 설정 하이브리드 인증 방식 적용

src/app/review/components/MyReviewAddForm.jsx, src/app/review/components/MyReviewDetail.jsx, src/app/review/components/MyReviewEditForm.jsx, src/app/review/css/UserReviewDetail.css
fix: 수정 완료 모달 생성 시 자동으로 수정 사이드 바와 수정 완료 모달이 사라지는 문제 해결
-  등록 시 메인 화면 클릭 시 취소 되는 문제 완화
- 유저 상세 리뷰 사이드 바 스크롤이 안되는 문제 해결
feat: 등록 중, 수정 중 로딩 창 생성
-   상세 리뷰 글 1000자 초과 시 경고 모달 생성 기능 추가
=> fix: 기능 개선

src/app/post/[id]/page.jsx, src/app/post/components/Editor.jsx, src/app/post/page.jsx, src/app/post/write/page.jsx
- 공동구매 -> 경매로 변경되어 경매 페이지 추가
- 작성페이지 , 상세조회 , 목록조회 페이지 구현
=> feat:경매페이지 추가

next.config.mjs, package-lock.json, package.json, src/app/ClientLayout.jsx, src/app/chat/components/ChatActionMenu.jsx, src/app/chat/components/ChatInput.jsx, src/app/chat/components/ChatList.jsx, src/app/chat/components/ChatListEmpty.jsx, src/app/chat/components/ChatListHeader.jsx, src/app/chat/components/ChatListSideBar.jsx, src/app/chat/components/ChatMessageItem.jsx, src/app/chat/components/ChatMessageList.jsx, src/app/chat/components/ChatProductInfo.jsx, src/app/chat/components/ChatRoom.jsx, src/app/chat/components/ChatRoomCard.jsx, src/app/chat/components/ChatRoomSidebar.jsx, src/app/chat/hooks/useWebSocket.js, src/app/chat/hooks/useWebSocketManager.js, src/app/main/page.jsx, src/app/product/[id]/page.jsx, src/components/common/Header.jsx, src/components/common/Sidebar.jsx, src/lib/api.js, src/lib/websocketManager.js, src/store/userStore.js
채팅 리스트 사이드바 (ChatListSidebar)
내 채팅방 목록 조회 및 표시
- 인증 상태에 따라 목록 갱신 (checkAuthStatus 연동)
- 새로고침 버튼 및 로딩/빈 상태 UI 처리
- 채팅방 클릭 시 ChatRoomSidebar 열림
채팅방 사이드바 (ChatRoomSidebar)
- 선택한 채팅방 메시지/참여자 정보 표시
- 메시지 전송 시 하단 입력폼(ChatInput)과 연동
채팅 메시지 UI
- ChatMessageList: 메시지 목록 렌더링, 날짜 구분, 송신자 구분
- ChatMessageItem: 본인/상대 메시지 스타일 구분
- ChatProductInfo: 상품 관련 정보 블록 표시
채팅 입력폼 (ChatInput)
- 메시지 입력/전송 기능 (Enter → 전송, Shift+Enter → 줄바꿈)
- 글자수 카운터(최대 1000자)
- 판매완료/미연결 상태일 때 비활성화 처리
채팅 액션 메뉴 (ChatActionMenu)
- 메시지별 액션 버튼(삭제, 신고, 차단 등) UI 추가
공통 요소
- Sidebar 컴포넌트 재사용
- lucide-react 아이콘 적용
- Badge 컴포넌트로 안읽은 메시지 카운트 표시
- useSidebar, useUser, useIsAuthenticated, useCheckAuthStatus 훅 활용
기타 개선 사항
- 파일명 정규화: ChatListSideBar.jsx → ChatListSidebar.jsx
- WebSocket 연결 후 chatRoomOpened 이벤트로 자동 스크롤 동작 추가
- API 연동: …
=> feat: 채팅 UI 컴포넌트 및 사이드바/입력 기능 구현

src/app/ClientLayout.jsx, src/app/product/[id]/page.jsx, src/app/product/components/AddressSearch.jsx, src/app/product/form/page.jsx, src/app/product/search/page.jsx, src/components/common/Header.jsx, src/components/common/ProductCard.jsx, src/enums/productStatus.js, src/enums/tradeStatus.js, src/lib/api.js, src/store/categoryStore.js, src/store/userStore.js, src/utils/format.js, src/utils/groupCategoryData.js
=> modify: 상품 상세 페이지 api 연동

src/app/(user)/login/login.css, src/app/(user)/mypage/page.jsx, src/app/ClientLayout.jsx, src/lib/api.js, src/store/mypageStore.js, src/store/userStore.js
- userStore의 persist 설정에 isAuthenticated 필드 추가로 새로고침 시 로그인 상태 유지
- localStorage에 null 값 저장 방지를 위한 partialize 로직 개선
- 로그아웃 시 localStorage 완전 정리 및 WebSocket 연결 해제
- api.js 인터셉터에서 zustand store와 localStorage 이중 토큰 검색 로직 구현
- 마이페이지 컴포넌트의 인증 플로우 개선 (로딩 상태 및 리다이렉트 처리)
- mypageStore에서 백엔드 응답 구조에 맞춘 데이터 매핑 로직 구현
- React key warning 해결을 위한 고유 key 추가
- 비인증 사용자 접근 허용 및 로그아웃 리다이렉션 추가
- userStore에 불필요한 API 호출을 막는 checkAuthStatusSilently 함수 추가
- ClientLayout에서 해당 함수를 호출하여 비로그인 상태에서도 401 에러 없이 메인 페이지에 접근 가능하도록 수정
- 로그아웃 시 무조건 메인 페이지(/)로 리다이렉션되도록 로직 수정
주요 해결 사항:
- 401 Unauthorized 에러로 인한 마이페이지 접근 불가 문제 해결
- 새로고침 시 로그인 상태 초기화 문제 해결  
- 로그아웃 후 localStorage 잔여 데이터 문제 해결
- 거래지역 정보 표시 누락 문제 해결
- 비인증 사용자 접근 허용 및 로그아웃 리다이렉션 추가
=> feat: 마이페이지 인증 시스템 구현 및 사용자 인증 플로우 개선

src/api/chatApi.js, src/app/ClientLayout.jsx, src/app/chat/api/chatApi.js, src/app/chat/components/ChatInput.jsx, src/app/chat/components/ChatList.jsx, src/app/chat/components/ChatListSideBar.jsx, src/app/chat/components/ChatMessageItem.jsx, src/app/chat/components/ChatProductInfo.jsx, src/app/chat/components/ChatRoomCard.jsx, src/app/chat/components/ChatRoomSidebar.jsx, src/app/chat/hooks/useWebSocketManager.js, src/app/product/[id]/page.jsx, src/components/common/Header.jsx, src/lib/api.js, src/lib/websocketManager.js, src/store/categoryStore.js
- 판매자인 경우에만 판매완료 버튼이 보이도록 수정
- 판매완료 버튼 클릭 시 채팅방에 판매완료를 알려주는 메시지를 상대방에게 전송
- 판매완료 후에도 채팅이 가능하게끔 수정
- 채팅방 및 채팅 메시지가 간헐적으로 2개씩 생성 및 저장되는 오류 수정
=> modify: 웹소켓 연결 및 인증 시 Header 정보를 가져오도록 수정

src/app/ClientLayout.jsx, src/app/chat/components/ChatInput.jsx, src/app/chat/components/ChatRoomSidebar.jsx, src/app/loading/loading.jsx
- clientLayout 페이지에서 로딩페이지 적용되게 수정
=> fix: 채팅방 초기 생성 시 초기 메시지가 전송되지않고 입력창에 적용되도록 수정

src/app/chat/api/chatApi.js, src/app/chat/components/ChatList.jsx, src/app/chat/components/ChatRoomCard.jsx, src/app/chat/components/ChatRoomSidebar.jsx
- 채팅방 목록 페이지에서 사용자 프로필 URL을 받아오도록 변경
- 채팅방을 생성할때 메시지를 보낼때 채팅방이 생성되도록 수정
=> 채팅방 목록에서 사용자 프로필 url 받아오도록 수정

src/app/main/page.jsx, src/app/product/form/form.css, src/app/product/form/page.jsx
- 판매하기 버튼 클릭 시 등록 완료 모달창 노출
- 판매하기 버튼 클릭 시 등록 로딩 이미지 추가
=> modify: 상품 등록 페이지 수정

src/app/(user)/components/formValidation.js, src/app/(user)/find-account/page.jsx, src/app/(user)/login/page.jsx, src/app/(user)/mypage/page.jsx, src/app/(user)/profile-edit/page.jsx, src/app/(user)/signup/complete/page.jsx, src/app/(user)/signup/page.jsx, src/components/common/Header.jsx, src/lib/api.js, src/store/userStore.js
**API 연동 수정:**
- 회원가입 401 에러 해결 (Gateway 인증 필터 예외 처리)
- 백엔드 DTO 구조 맞춤 및 데이터 변환 최적화
- API 인터셉터 인증 로직 개선
**UX/플로우 개선:**
- 회원가입 완료 후 버튼 텍스트 개선 (로그인하기 → 서비스 시작하기)
- 로그인 상태에서 로그인 페이지 자동 리다이렉트
- 신규 회원 마이페이지 로딩할 정보 없어서 나는 에러 처리 해결
**기술적 개선:**
- 타임아웃 에러 처리 강화 (로그아웃/대시보드)
- 불필요한 alert 제거
- 폼 검증 유틸리티 파일명 개선 (emailUtils → formValidation)
- 중복 코드 정리
=> fix: 회원가입/로그인 플로우 및 에러 처리 개선
